// Single source of truth in @benkalegin/doodles-core. clouddiagram editor
// re-exports them here for backwards-compatible local import paths. Anything
// not (yet) in doodles-core stays locally defined below.

export {
    type Id,
    ElementType,
    type ElementRef,
    PortAlignment,
    FlowchartNodeKind,
    type ColorSchema,
    type LineStyle,
    PictureLayout,
    type CustomShape,
    type DiagramElement,
    type Package,
    type PortState,
    type HasColorSchema,
    type GanttTaskStatus,
    type GanttTaskState,
    type GanttDependencyState,
    type ClassMemberKind,
    type ClassMemberState,
    type ErAttributeState,
    type ErEntityState,
    type ErCardinality,
    type ErRelationshipState,
    type PieSliceState,
    type NodeState,
    RouteStyle,
    TipStyle,
    defaultRouteStyle,
    CornerStyle,
    defaultCornerStyle,
    defaultNoteStyle,
    defaultNoteWidth,
    defaultNoteHeight,
    type LinkState,
} from "@benkalegin/doodles-api";
